# sudo: required
language: node_js

node_js:
  - 12

# services:
#   - xvfb

# # dist: trusty
# addons:
#   chrome: stable

# before-install:
#   - 'sudo chown root /opt/google/chrome/chrome-sandbox'
#   - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
#   - npm run dev &
install:
  - npm install -g codecov

script:
  - npm test && codecov
