addons:
  sauce_connect: true

language: node_js

node_js:
  - 12

install:
  - npm install -g nightwatch

before_script:
  - npm run serve:dist &

script:
  - nightwatch --config nightwatch.js
  - pkill node
