# sudo: required
language: node_js

node_js:
  - 12

services:
  - xvfb

addons:
  chrome: stable

before-install:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - yarn run test
